App\Entity\Location:
  properties:
    latitude:
      - Range:
          min: -90
          max: 90
          groups: ['new', 'edit']
    longitude:
      - Range:
          min: -180
          max: 180
          groups: [ 'new', 'edit' ]

App\Entity\Measurement:
  properties:
    temperature:
      - Range:
          min: -30
          max: 50
          groups: ['new', 'edit']
