#index:
#    path: /
#    controller: App\Controller\DefaultController::index

weather_in_city:
  path: /weather/{city}
  controller: App\Controller\WeatherController:cityAction
  requirements:
    city: \d+

weather_in_country_city:
  path: /weather/{countryCode}/{city}
  controller: App\Controller\WeatherController:countryCityAction
  requirements:
    countryCode: '[A-Z]{2}'
    city: '[a-zA-Z]{2,15}'

app_logout:
  path: /logout
  methods: GET